name: Security Pipeline

on:
  push:
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GitLeaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: shopNow
          format: json
          output: trivy-fs-report.json
          severity: HIGH,CRITICAL
          exit-code: 0

      - name: Build Backend Image
        run: docker build -t shopnow-backend:v1 ./shopNow/backend

      - name: Build Frontend Image
        run: docker build -t shopnow-frontend:v1 ./shopNow/frontend

      - name: Build Admin Image
        run: docker build -t shopnow-admin:v1 ./shopNow/admin

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: shopnow-backend:v1
          severity: HIGH,CRITICAL
          format: json
          output: backend-report.json
          exit-code: 0

      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: shopnow-frontend:v1
          severity: HIGH,CRITICAL
          format: json
          output: frontend-report.json
          exit-code: 0

      - name: Scan Admin Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: shopnow-admin:v1
          severity: HIGH,CRITICAL
          format: json
          output: admin-report.json
          exit-code: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Generate Reports
        run: |
          python scripts/report_generator.py

      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python scripts/slack_notify.py

      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            backend-report.json
            frontend-report.json
            admin-report.json
            trivy-fs-report.json
            reports/summary-report.json
            reports/consolidated-report.html