name: Security Pipeline

on:
  push:
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Secret Scanning
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Filesystem Vulnerability Scan
      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: shopNow
          format: table
          severity: HIGH,CRITICAL
          exit-code: 0

      # Build Backend Image
      - name: Build Backend Image
        run: docker build -t shopnow-backend:v1 ./backend

      # Build Frontend Image
      - name: Build Frontend Image
        run: docker build -t shopnow-frontend:v1 ./frontend

      # Build Admin Image
      - name: Build Admin Image
        run: docker build -t shopnow-admin:v1 ./admin
      # Scan Backend Image
      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: shopnow-backend:v1
          severity: HIGH,CRITICAL
          format: json
          output: backend-report.json
          exit-code: 0

      # Scan Frontend Image
      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: shopnow-frontend:v1
          severity: HIGH,CRITICAL
          format: json
          output: frontend-report.json
          exit-code: 0

      # Scan Admin Image
      - name: Scan Admin Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: shopnow-admin:v1
          severity: HIGH,CRITICAL
          format: json
          output: admin-report.json
          exit-code: 0

      # Upload Reports
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            backend-report.json
            frontend-report.json
            admin-report.json